version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3307:3306'
    volumes:
      - ./db_data:/var/lib/mysql